always_pending:
  title_regex: '(WIP|wip)'
  labels:
    - wip
approve_by_comment: true
approve_regex: ^[Aa]pproved
reject_regex: ^[Rr]ejected
reset_on_push: true
reviewers:
  -
    name: backend
    required: 0
    members:
      - iceb0y
    conditions:
      branches:
        - master
      files:
        - "*.py"
  -
    name: frontend
    required: 1
    members:
      - breeswish
    conditions:
      branches:
        - master
      files:
        - "vj4/ui/*"
        - "package.json"
        - "npm-shrinkwrap.json"
  -
    name: project
    required: 2
    members:
      - breeswish
      - iceb0y
      - twd2
    conditions:
      branches:
        - master
      files:
        - ".pullapprove.yml"
