parser: babel-eslint
plugins:
  - babel
  - react
env:
  browser: true
  es6: true
  jquery: true
  commonjs: true
extends:
  - airbnb
  - plugin:react/recommended
parserOptions:
  sourceType: module
  ecmaVersion: 7
  ecmaFeatures:
    - impliedStrict
    - experimentalObjectRestSpread
    - jsx
globals:
  __webpack_public_path__: true
  __webpack_require__: true
  UiContext: true
  Context: true
rules:
  no-unused-vars: warn
  no-console: off
  indent:
    - error
    - 2
    - { SwitchCase: 0 }
  func-names:
    - off
