parser: babel-eslint
plugins:
  - babel
  - react
env:
  browser: true
  es6: true
  jquery: true
  commonjs: true
extends:
  - airbnb
parserOptions:
  sourceType: module
  ecmaVersion: 7
  ecmaFeatures:
    - impliedStrict
    - experimentalObjectRestSpread
    - jsx
globals:
  __webpack_public_path__: true
  __webpack_require__: true
  UiContext: true
  UserContext: true
  Context: true
rules:
  no-unused-vars: warn
  no-console: off
  no-underscore-dangle: off
  func-names: off
  indent:
    - error
    - 2
    - { SwitchCase: 0 }
  max-len:
    - error
    - 150
  react/prefer-stateless-function: off
